### ISSUE TITLE
Uploading new versions of documents

### ISSUE THREAD

**Issue by ThomasIAm** [Bloemendaal/Windesheim-ELO#18]
If a hand-in assignment allows you to upload new versions after you've submitted the first document, the upload button/field should remain. Currently, it disappears after you've submitted the first document. However, this is not always the required behavior.

See this screenshot of the original ELO below:
![image](https://user-images.githubusercontent.com/10333951/65325362-e8522200-dbae-11e9-9613-f8149d5590cd.png)
I have submitted this document multiple times and it still allows me to upload and submit new versions.

**Comment by Bloemendaal** [comment]
Thanks for submitting this issue! In order to fix this, I need either the JSON files that are loaded (tab network in your console) or the course so I can check it out myself.

**Comment by ThomasIAm** [comment]
This is on the IDS Project 1 (PP1) course. I'm not entirely sure what JSON response you want, maybe you can point me in the right direction?

**Comment by Bloemendaal** [comment]
Unfortunately, I do take that course. If you open the developer console (F12), go to the tab network and make sure it is recording. Press the submittion button in the menu and the ELO should navigate to `LoadUserHandinDetails`, as shown in the picture below.
I need that response JSON to debug this problem. You can censor out any personal detail by just replacing it with string, int or boolean.
I assume we're looking for the property `IS_INITIAL` or `HANDIN_TYPE`... 

![image](https://user-images.githubusercontent.com/1348606/65638014-8d249300-dfe5-11e9-8485-f4bbe18b56df.png)

If you have any trouble, please send me the URL of the hand-in point! :)

**Comment by ThomasIAm** [comment]
I'm very sorry for the late response. GitHub notifications seem to be turned off for my account. Is this the response you're looking for?

```
{
  "STUDYROUTE_USER_HANDINDETAILS":[
    {
      "ID":int,
      "TITLE":"1-PP",
      "STUDYROUTE_NAME":"IDS Project 1",
      "DESCRIPTION_DOCUMENT_URL":"/CMS/_STUDYROUTE_FOLDERS/7/I/ICT_/ICT.IDS.PP1.V19/IDS Project 1/IDS Project 1/_ASSIGNMENT_DEFINITION_DESCRIPTIONS/4986710.htm",
      "ASSIGNMENT_DOCUMENT_TYPE":-1,
      "INITIAL_DOCUMENT_STATUS":-1,
      "INITIAL_DOCUMENT_CPID":-1,
      "IS_INITIAL":1,
      "HANDIN_DATE":"\/Date(1571954774860)\/",
      "HANDIN_URL":"/CMS/DPF/98152/Windesheimportfolio/Courses/IDS Project 1/Inleveropdracht/1b-gr5-PP-v0.9.docx",
      "HANDIN_NAME":"1b-gr5-PP-v0.9.docx",
      "HANDIN_TYPE":0,
      "REVIEW_TYPE":-1,
      "REVIEW_PUBLISHED":1,
      "NATSCHOOL_STATUS":-3,
      "ASSIGNMENT_SUBMITTED_PACKAGE_ID":1369757,
      "XCAS_CONTENTPACKAGEVERSION_ID":31970129,
      "XCAS_CONTENTPACKAGEVERSION_NAME":"0.0.0.1"
    }
  ]
}
```

**Comment by Bloemendaal** [comment]
Nu dat de MD ELO het weer doet, zal ik er in de kerstvakantie voor je naar kijken!

**Comment by Bloemendaal** [comment]
Helaas is hierover ook niet veel goeds te zeggen. Er wordt in deze JSON niet aangegeven of je een document meerdere keren mag uploaden. Zelfde geldt voor een mogelijke deadline. Het enige dat ik kan doen is het uploadpunt altijd opengooien, ook na het inleveren (geeft dan hetzelfde effect als gesloten inleverpunten als meerdere keren inleveren niet toegestaan is).
Laat maar weten wat je het liefst hebt. Gelukkig komt er toch binnenkort een nieuwe ELO :)

**Comment by ThomasIAm** [comment]
Lekker zo laten toch. Zeker inderdaad omdat er toch een nieuwe ELO aan komt.
