### ISSUE TITLE
404 voor al het studiemateriaal

### ISSUE THREAD

**Issue by Gerjan98** [Bloemendaal/Windesheim-ELO#20]
Bij alle bestanden die ik open krijg ik een 404, na het uitschakelen van de chrome extensie werkt het naar behoren.

![image](https://user-images.githubusercontent.com/24853786/66989786-5235ec80-f0c5-11e9-91fb-bcbe4352df84.png)

URL waar ik naar toegestuurd word is als volgt:
https://elo.windesheim.nl/CMS/_STUDYROUTE_FOLDERS/7/I/ICT_/ICT.SE.UML.V19/Ontwerpen%20met%20Unified%20Modelling%20Language/Ontwerpen%20met%20Unified%20Modelling%20Language/_PREFACE_ITEM

De juiste url:
https://elo.windesheim.nl/CMS/_STUDYROUTE_FOLDERS/7/I/ICT_/ICT.SE.UML.V19/Ontwerpen%20met%20Unified%20Modelling%20Language/Ontwerpen%20met%20Unified%20Modelling%20Language/2ef4d0ab/Studiehandleiding%20UML_20192020.pdf

**Comment by Gerjan98** [comment]
Aaah jammer, naja dan maar wachten tot dat gefixed is. Wat is het ook een mooi platform :)

**Comment by ThomasIAm** [comment]
De mobiele versie is sinds kort geupdate! Het openen van links werkt weer, dus ik hoop dat je de extensie nu weer werkend kunt krijgen. Voor de goede orde: de extensie werkt momenteel dus niet.

**Comment by Bloemendaal** [comment]
> De mobiele versie is sinds kort geupdate! Het openen van links werkt weer, dus ik hoop dat je de extensie nu weer werkend kunt krijgen. Voor de goede orde: de extensie werkt momenteel dus niet.

Bedankt voor het doorgeven!
