### ISSUE TITLE
Loguit knop

### ISSUE THREAD

**Issue by ThomasIAm** [Bloemendaal/Windesheim-ELO#22]
Deze issues zijn inmiddels meer feature requests geworden dan wat anders...

... maar een uitlog knop zou wel chill zijn.

**Comment by Bloemendaal** [comment]
Ik denk niet dat dit mogelijk is. De ELO heeft zelf ook geen uitlog knop en alle cookies wissen is ook niet echt een goede oplossing. Ik heb gekeken naar de WIP maar deze inlogsystemen komen maar voor een deel overeen. Dat betekent dat alleen wanneer je eerst bij WIP inlogt en dan via de ELO uitlogt dat het werkt, maar wanneer je niet via WIP gaat dat de ELO zichzelf niet wil uitloggen...
