### ISSUE TITLE
Geen klassencode.

### ISSUE THREAD

**Issue by MartyUtloo** [Bloemendaal/Windesheim-ELO#29]
In de normale ELO zie je ook de klascode van het vak. Als je meerdere courses hebt met dezelfde naam is dat nogal verwarrend.

**Comment by Bloemendaal** [comment]
De reden hiervoor is dat deze gegevens niet meegestuurd worden in de JSON response helaas. De extensie gebruikt de mobiele routes en zoals je ziet zullen deze course codes ook niet op mobiel weergegeven worden. Helaas! :(

![image](https://user-images.githubusercontent.com/1348606/86349371-42fdcb80-bc61-11ea-8643-8772c6ccced9.png)
